service.pod.name.prefix=option.trading

option.trading.user.id=TOC072
option.trading.user.api.secret=2ibr5lqcywqzyzonsqgomvc949oshq64
option.trading.user.api.key=zyppp731lbi6co2g
option.trading.eligible.instruments=NIFTY 50,NIFTY BANK
option.trading.user.public.token=ixgaAVW8ZftbpC2VbkfiHteZtv44mDcv
option.trading.user.access.token=NJyEeJ43v28fWVKOSXA5Z8b0EqwzUzPT

option.trading.project.id=fifth-curve-382514
option.trading.subscription.id=options-data-topic
option.trading.current.expiry=26317
#format : yymdd
#format2 month end: yyMMM e.g 23APR

option.trading.index.map=NIFTY 50:1,NIFTY BANK:2
option.trading.option.search.index.1=NIFTY
option.trading.option.search.index.2=BANKNIFTY
option.trading.strike.difference.1=50
option.trading.strike.difference.2=100

option.trading.straddler.run.backtest=false;

